name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4.1.1
        with:
          days-before-issue-stale: 35
          days-before-issue-close: 7
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale with no activity. It will close in 7 days."
          close-issue-message: "This issue has been automatically closed."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: help wanted
          repo-token: ${{ secrets.GITHUB_TOKEN }}
