name: Send issue to Discord
on:
  issues:
    types:
      - opened
jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "${{github.event.issue.title}}"
              }
            ]
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "New grant application"
